version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: microservice-dev
    user: root
    environment:
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: microservice-db
    restart: always
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: 